### ISSUE TITLE
Fix jsx-a11y problems and enforce those rules

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#12954]
We now have ` jsx-a11y` plugin which can check accessibility in jsx elements we create. However we currently break some rules and therefore these rules are not enforced yet. Anyone who is a bit interested feel free and have a go :)

How to find where it is broken:
1. Pick some rule from the list below
2. Remove line with that rule from `.eslintrc.json`
3. run `npm run eslint` to see where this rule is broken

You can read about those rules in https://github.com/evcohen/eslint-plugin-jsx-a11y/tree/master/docs/rules

Note: Fixing some findings is super simple, some require a bit of playing with the code and some are not worth fixing and need to be replaced with something more sensible (like we implement custom dropdown and we should just use \<select\>).

TODO:
- [ ] jsx-a11y/anchor-is-valid (6)                                             
- [x] jsx-a11y/alt-text (8) [#13069]                                                  
- [x] jsx-a11y/click-events-have-key-events (6) [#13996]                        
- [x] jsx-a11y/label-has-associated-control (5) [#13070]                         
- [ ] jsx-a11y/no-autofocus (1)                                                 
- [x] jsx-a11y/no-noninteractive-element-interactions (2) [#13996]                      
- [x] jsx-a11y/no-static-element-interactions (1)                               
- [x] jsx-a11y/no-interactive-element-to-noninteractive-role (1) (https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/577)               
- [x] jsx-a11y/no-onchange (1) (https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/398)[#15667]

**Comment by marusak** [comment]
No, this should not be reopened. 5608bca was a commit which removed the last rule override and now we enforce all of those rules.
