### ISSUE TITLE
@nondestructive test cleanups

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13717]
This is a meta-bug for things that cross my mind (and my eyes in PR reviews):

 - [x] Introduce a helper for sedding a file and restoring it: PR #13725 
 - [x] Introduce a helper for backing up/restoring a directory:  PR #13751 
 - [ ] Generalize `TestMachines.addIface()` (introduced in PR #13699): PR #13788
 - [x] Fix SELinux disabling in `installWithErrorTest` (use `chcon`): We may just be able to [drop this completely](https://github.com/cockpit-project/cockpit/pull/13699#discussion_r392837894) ← we did that
 - [x] Try and drop allowBugErrors() in machineslib.py: PR #13747
