### ISSUE TITLE
remove Moment.js

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15979]
Moment.js [has been deprecated](https://momentjs.com/docs/#/-project-status/). We should switch to something else. See Moment's suggested list @ https://momentjs.com/docs/#/-project-status/recommendations/

Ideally, we could just use native JavaScript date & time functions. They're much better now (and supported in every browser) than when moment.js was first made. If not native, we should use something that's a small wrapper and has parts we can pick and choose (date-fns for example).

Absolute times (convert to `Intl.DateFormat`):
 - [x] Accounts page: #16002 
 - [x] Metrics page: #16015
 - [x] Common library, Overview/Logs pages: #16019
 - [x] Hardware Info: #16029
 - [x] Shutdown dialog (non-trivial, as current date picker is broken), blocked on #16053
 - [x] Plots, Services: PR #16028 
 - [x] SELinux: PR #16036

Time durations (not covered by `Intl.DateFormat`):
- [ ] Storage: Blocked on #15937 and #15968: #16097
- [x] Uptime on Overview: #16084
- [x] Updates: #16090

**Comment by martinpitt** [comment]
Indeed the `Intl` class looks quite sufficient for absolute date/time display:

```js
new Intl.DateTimeFormat('de', { dateStyle: "short", timeStyle: "short"}).format(d)
"26.06.21, 10:45"
new Intl.DateTimeFormat('en', { dateStyle: "short", timeStyle: "short"}).format(d)
"6/26/21, 10:45 AM"
new Intl.DateTimeFormat('zh-CN', { dateStyle: "short", timeStyle: "short"}).format(d)
"2021/6/26 上午10:45"
```

So we can at least start with replacing these. Maybe we need to have a little wrapper in pkg/lib/ which will use `cockpit.language` and provide a collection of default options so that we retain some consistency. We currently call `moment.format(...)` with a wildly differing set of options, maybe we can clean this up a little bit. Although on first sight this may actually be justified..

We use durations in 4 places in our code (packagekit, 2x storaged, overview), `Intl` has no counterpart for this. But that would at least reduce moment usage quite a bit, and we can look for a small replacement lib for these cases.

**Comment by martinpitt** [comment]
I ported the accounts page in #16002, comments appreciated.
