### ISSUE TITLE
master → main TODO list

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#16039]
## cockpit
 - [x] rename to main
 - [x] fix bugs in workflows and integration tests
 - [x] https://github.com/cockpit-project/cockpit/pull/16040

## weblate
 - [x] rename to main
 - [x] update weblate settings
 
## cockpituous
 - [x] change default branch name in release-runner (which seems not to be used, since we always use a tag)
 - [x] rename cockpituous to main
 - [x] update urls in docs and scripts
 - [x] rebuild release container, deploy → https://github.com/cockpit-project/cockpituous/actions/runs/998017057
 - [x] rebuild tasks, deploy → https://github.com/cockpit-project/cockpituous/actions/runs/998016782
 - [x] rebuild images, deploy → https://github.com/cockpit-project/cockpituous/actions/runs/998018995
 - [x] land cockpit-project/cockpituous#425

## bots
 - [x] rename bots to main
 - [x] update cockpit's `tools/make-bots`
 - [x] update default branch selection in webhook
 - [x] probably more cockpituous updates
 - [x] update urls in docs and scripts
 - [x] https://github.com/cockpit-project/bots/pull/2177

## container
 - [x] rename cockpit-container to main
 - [x] update dockerhub config, or will it just follow the default branch?

## ostree

 - [x] rename
 - [x] pick up the pieces https://github.com/cockpit-project/cockpit-ostree/pull/189
 - [x] weblate repo rename
 - [x] update settings on weblate (blocked: only @marusak has credentials for that, and he's on holiday)

## podman

 - [x] rename
 - [x] pick up the pieces https://github.com/cockpit-project/cockpit-podman/pull/734
 - [x] weblate repo rename
 - [x] update settings on weblate

## starter-kit

 - [x] rename
 - [x] pick up the pieces https://github.com/cockpit-project/starter-kit/pull/472

## composer

 - [x] rename
 - [x] pick up the pieces https://github.com/osbuild/cockpit-composer/pull/1318
 - [x] weblate repo rename
 - [x] update settings on weblate

**Comment by marusak** [comment]
@allisonkarlitskaya I believe that the remaining issues were all addressed. I don't want to just mark them as done, maybe I don't understand all the details. Can you please take a look?

**Comment by martinpitt** [comment]
I was part of that -- I just double-checked the weblate repos for ostree and composer, and they are all up to date wrt. main renaming.
