### ISSUE TITLE
Consider oxlint/biome as replacement of eslint

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#20279]
oxlint is an oxidized eslint written in Rust. It is vastly faster then eslint ~ 72 ms versus 17 seconds but as of now supports less rules.

So for us to switch we need to make sure all our plugins and rules are supported, this issue should track that. Our used plugins:

* [ ] [eslint-plugin-import](https://github.com/oxc-project/oxc/issues/1117)
   * [ ] import/export
   * [ ] import/first
   * [ ] import/no-absolute-path
   * [ ] import/no-named-default
   * [x] import/no-webpack-loader-syntax
* [ ] [eslint-plugin-jsx-a11y](https://github.com/oxc-project/oxc/issues/1141)
* [ ] [eslint-plugin-n](https://github.com/oxc-project/oxc/issues/493)
* [x] eslint-plugin-promise
  - [ ] no-nesting 
* [ ] [eslint-plugin-react](https://github.com/oxc-project/oxc/issues/1022)
  - [x] jsx-boolean-value
  - [ ] jsx-closing-bracket-location
  - [ ] jsx-closing-tag-location
  - [ ] jsx-curly-brace-presence
  - [ ] jsx-curly-newline
  - [ ] jsx-curly-spacing
  - [ ] jsx-equals-spacing
  - [ ] jsx-first-prop-new-line
  - [ ] jsx-fragments
  - [ ] jsx-handler-names
  - [ ] jsx-indent
  - [ ] jsx-indent-props
  - [ ] jsx-no-bind
  - [ ] jsx-pascal-case
  - [ ] jsx-props-no-multi-spaces
  - [ ] jsx-tag-spacing
  - [ ] jsx-uses-react
  - [ ] jsx-uses-vars
  - [ ] jsx-wrap-multilines
  - [ ] no-danger-with-children
  - [ ] no-did-update-set-state
  - [ ] no-unused-prop-types
  - [ ] prop-types
  - [x] self-closing-comp
* [ ] [eslint-plugin-react-hooks](https://github.com/oxc-project/oxc/issues/2174) (only react-hooks/exhaustive-deps missing)
* [ ] [eslint-plugin-core](https://github.com/oxc-project/oxc/issues/479)
* [ ] [eslint-typescript](https://github.com/oxc-project/oxc/issues/2180)

Apart from speed, oxlint found issues which eslint did not catch:

* https://github.com/cockpit-project/cockpit/pull/20254
* https://github.com/cockpit-project/cockpit/pull/20273

Another benefit is that oxlint provides a native language-server while for eslint you need an alternative [extension](https://github.com/Microsoft/vscode-eslint). While for oxlint you can use the native Rust binary for example in [neovim](https://github.com/jelly/Dotfiles/commit/9924ec1ef8785185c6cab8410589864df042f710).

Listing the rules we have enabled:

```
npm run eslint --print-config .eslintrc.json > eslint-custom-conifg.json
# number of rules enabled
cat eslint-custom-conifg.json | jq -r '.rules | length'
# rule names
cat eslint-custom-conifg.json | jq -r '.rules | keys | join("\n")'
```

React to-do generated with:
```
npx eslint --print-config .eslintrc.json | jq -r '.rules | keys | join("\n")'  | grep --color=never react | sed 's/react\///' | sed 's/-/_/g' > rules.txt
```

In oxlint git
```
for x in $(cat ~/projects/starter-kit/rules.txt); do git grep -q $x || echo "  - [ ] $x" | sed 's/_/-/g'; done
```

**Comment by jelly** [comment]
From eslint-plugin-promise we use `param-names` which is now implemented in https://github.com/oxc-project/oxc/pull/4293 and merged.

**Comment by jelly** [comment]
@Venefilyn mentioned biome a few times 😄 it has:

* a formatter
* a linter for CSS/JS
* import sorter (seems to be separate from linter)

And in general is funded, which oxlint might not, they don't have a formatter (yet) and development seems slow.

We should figure out if biome can provide us with:

* [ ] the import order sorting which we have [now](https://github.com/cockpit-project/cockpit-files/blob/main/.eslintrc.json#L15)
* [ ] react hooks rules, these are really useful imo
* [ ] a11y rules
* [ ] react rules
* [ ] adjust the formatting to our existing style
* [ ] LSP, this is really required these days I'd say oxc has one.
* [ ] CSS, can it replace stylelint?
     * [ ] so [logical-spec plugin](https://github.com/cockpit-project/cockpit-files/blob/main/.stylelintrc.json#L4)
     * [ ] [our normal rules](https://github.com/cockpit-project/cockpit-files/blob/main/.stylelintrc.json#L2)

**Comment by jelly** [comment]
Stylelint [rule overview](https://stylelint.io/user-guide/rules/) and [recommended rules we enabled](https://github.com/stylelint/stylelint-config-recommended/blob/main/index.js). Biome only seems to implement a subset.

**Comment by TheAlexLichter** [comment]
As a heads-up regarding oxlint - you can also gradually migrate and automatically disable all supported oxlint rules in ESLint [through this ESLint plugin](https://github.com/oxc-project/eslint-plugin-oxlint)!

**Comment by jelly** [comment]
To summarize our potential switching, we have now enabled eslint-plugin-typescript in cockpit-files with the [recommended rules](https://typescript-eslint.io/rules/) so our needs kinda changed. I wrote a [summary] down in a cockpit-files Pr.

**Comment by TheAlexLichter** [comment]
You could try Oxlint's [type-aware linting preview](https://voidzero.dev/posts/announcing-oxlint-type-aware-linting) to use type-aware linting with Oxlint, supporting 40 typescript-eslint rules (and ideally covers your needs) 👏

**Comment by jelly** [comment]
Current state of biome (2.5.13) is:

```
  ℹ These rules have not yet been implemented:

  - accessor-pairs
  - camelcase
  - new-cap
  - no-caller
  - no-delete-var
  - no-extra-bind
  - no-invalid-regexp
  - no-iterator
  - no-new-object
  - no-new-symbol
  - no-octal
  - no-unexpected-multiline
  - no-unreachable-loop
  - no-useless-call
  - prefer-promise-reject-errors
  - unicode-bom
  - import/export
  - import/no-absolute-path
  - import/no-duplicates
  - import/no-named-default
  - import/no-webpack-loader-syntax
  - jsx-a11y/label-has-for
  - n/handle-callback-err
  - n/no-callback-literal
  - n/no-deprecated-api
  - n/no-exports-assign
  - n/no-new-require
  - n/no-path-concat
  - n/process-exit-as-throw
  - react/jsx-handler-names
  - react/jsx-no-undef
  - react/jsx-pascal-case
  - react/jsx-uses-react
  - react/jsx-uses-vars
  - react/no-deprecated
  - react/no-did-update-set-state
  - react/no-direct-mutation-state
  - react/no-find-dom-node
  - react/no-is-mounted
  - react/no-render-return-value
  - react/no-unescaped-entities
  - react/no-unused-prop-types
  - react/prop-types
  - react/react-in-jsx-scope
  - react/require-render-return
  - react/self-closing-comp
```

**Comment by jelly** [comment]
More missing is `eslint-plugin-import` that needs figuring out in biome, and stylelint rules.
