### ISSUE TITLE
login: add message for Internet Explorer deprecation

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#9689]
Generally, we should use feature detection to allow/deny web browsers to use Cockpit. This includes various checks, such as websocket, among others.

## Background

As we will be dropping support for Internet Explorer (at some time in the future, possibly even the very-near-future), we should have a friendlier message that communicates that their browser does not work and message which browsers do work (probably with some links to the browser vendors).

In the case of Internet Explorer, we might want to handle it with a special case, as it's shipped in all versions of Windows and is the default for all versions < 10. And Internet Explorer hasn't gotten updates in years now, with the exception of critical security updates (which are tied to the version of the OS it runs on).

Windows marketshare basically indicates that everyone using Windows has either stuck with Windows 7 or migrated to Windows 10, where Edge is the new default. So, in practice, the problems with Internet Explorer accessing Cockpit are limited to Windows 7 when using the default browser.

## To-do

First, a deprecation warning:

1. [x] Design deprecation warning
2. [x] Implement deprecation warning on login page

Secondly, an outright block:

3. [x] Design login blocker for IE, with recommended solution (alternate browsers)
4. [x] Implement IE block on login page

**Comment by garrett** [comment]
Useful features (for Cockpit at least) supported by every browser except Internet Explorer:

- [CSS feature queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) (also supported by JavaScript, by-the-way), allows us have browsers act one way if they support a feature and another if they do not. This is useful for taking advantage of new-ish features and having fallbacks without hard-to-maintain hacks.
- [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) lets us swap out values on the fly, based on context. The values of variables can be adjusted by CSS or JavaScript and the page instantly adapts.
- CSS [unset](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) and [inital](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) to reset properties (which would be super useful to undo parts of PatternFly where we need to do so)
- [HTML templates](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template)
- [Download attribute](https://developers.google.com/web/updates/2011/08/Downloading-resources-in-HTML5-a-download) (note: iOS Safari does not support this either, nor does it work cross-domain in other browsers)
- [Minimum length for HTML input fields](https://caniuse.com/#feat=input-minlength)
- [HTML5 meter element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter) (native progress bar / percent indicator)
- ES6 support (native, modern JavaScript)
- WebAssembly
- CSP level 2
- [wbr](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) (word break oppertunity)
- And [a lot more](https://caniuse.com/#compare=ie+11,edge+18,firefox+63,chrome+70,safari+TP) (scroll down to "Mixed support" and look at everywhere IE is red)

All of these features would signifcantly help us write more modern code. Checking for one or all of these features (especially using a feature query) also happen to target IE for removal.

**Comment by garrett** [comment]
Here's an actual screenshot from Internet Explorer:

![cockpit-ie](https://user-images.githubusercontent.com/10246/47648780-4cc15880-db7b-11e8-9bfa-a3c2b5a58c3d.png)
